### ISSUE TITLE
usage: hybrid mode 

### ISSUE THREAD

**Issue by LGG02** [paoloshasta/shasta#30]
Hi,

I have duplex and ULONT data and want to try shasta for generating phased assembly? Can I use both duplex and ULONT together for this purpose? 

If I want to generate phased assembly from duplex only, shall I use Nanopore-Phased-R10-Slow-Nov2022 or use HiFi config file in assembly mode=2?

**Comment by paoloshasta** [comment]
Shasta does not support hybrid assemblies. It expects a single population of reads at its input. This is an intentional design choice.

There is no assembly configuration for duplex reads and the assembly configuration for HiFi reads is very old and not extensively tested, so I don't recommend using it. So I am afraid this leaves you with no option to use Shasta "out of the box"  for the work you describe. 

However it may be possible to use one of the existing assembly configurations as a starting point to create a modified assembly configuration that works well with duplex reads. This would be a bit of a project, but I would be willing to help if you decide to embark in it.
